### ISSUE TITLE
Clicking Logo Blanks Page

### ISSUE THREAD

**Issue by jp-webdev** [cats-with-potatos/chat-app#9]
Hi guys,

If you click the chat-app logo when it is on Sample Page 1, it makes all of the content disappear. This can be remedied by reloading the page, or going to the signup page and coming back to that sample page.

**Comment by JGefroh** [comment]
The logo attempts to load the `chat-app` state, which is defined in `app.js`. `chat-app` is acting as a parent state for all other states in the application and isn't intended to be transitioned into directly - you'll notice all it has is a layout template. You'll want to create an actual "entry" page for the application.

One of the states for the `sample` module has a url of `/`, which will make it load by default. If you change that and create another state with `/` as the url, it should make it load by default instead of that one.

**Comment by IAmJohnOconnell** [comment]
I believe this is now closable. Someone else confirm?

**Comment by RafGDev** [comment]
Yes it is.
